##################################################
# Example SystemVerilog IP package Makefile
##################################################
PROJECT:=$(shell basename "${PWD}")
MODULE:= $(shell echo "${PROJECT}")
export PROJECT
export MODULE
include ../common.mk